# Done to increase the memory available to gradle.
# Optimized for 2GB RAM Linux environment
org.gradle.jvmargs=-Xmx1200M -XX:+UseG1GC -Dfile.encoding=UTF-8 -noverify
org.gradle.parallel=true
org.gradle.java.home=C:/Users/8523~1/AppData/Roaming/PRISML~1/java/JAVA-R~1

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.16.9

# Mod Properties
mod_version=0.1.0
maven_group=com.project3
archives_base_name=project3

# Dependencies
fabric_version=0.141.4+1.21.11
